### ISSUE TITLE
fmt/1441 - zip folders incorrect

### ISSUE THREAD

**Issue by richardlehane** [exponential-decay/skeleton-container-test-suite-generator#10]
This new signature has this folder structure: Metadata/Properties.plist; Index/Document.iwa 
The skeleton file generated has: Index/Metadata/Properties.plist; Index/Metadata/Document.iwa

**Comment by ross-spencer** [comment]
Thanks Richard, this should be solved by https://github.com/exponential-decay/skeleton-container-test-suite-generator/commit/e86a7b755a2993d6cccaf20a98bcae1de6d5fa16 

NB. I've cut a `main` branch for this repository now. I'll delete the `master` branch at some point in the future and think you might be the only affected. Just an FYI.
