### ISSUE TITLE
fmt/1352/fmt/1353: missing range: [\bXX-\bYY] syntax not yet handled by generator

### ISSUE THREAD

**Issue by richardlehane** [exponential-decay/skeleton-container-test-suite-generator#11]
This new signature starts with four 0s and then a range at the fifth offset: "\x05" - "\x0f".
The skeleton file has another zero byte at the fifth offset.

**Comment by ross-spencer** [comment]
Ack, yep. This looks like [newer syntax](https://github.com/digital-preservation/droid/blob/de8fca984c1ba2f6487579b7dc2e41136cf56fae/Signature%20syntax.md#byte-ranges-nm) that I haven't incorporated before. 

It looks like 1352 as well. And those look to be the only two using this version of a byte range. 
```
$:/tmp$ cat cont | grep "\[" | sort | uniq
<Path>[Content_Types].xml</Path>
<Sequence>00 00 00 00 [01-04]</Sequence>
<Sequence>00 00 00 00 [05-0F]</Sequence>
<Sequence>10 00 00 00 'Word.Document.' ['6'-'7']
<Sequence>10 00 07 00 [00:FF] [00:FF] 00 </Sequence>
<Sequence>[&amp;01][&amp;01]</Sequence>
<Sequence>[&amp;01]</Sequence>
<Sequence>'office:version=' [22 27] '1.0' [22 27]</Sequence>
<Sequence>'office:version=' [22 27] '1.1' [22 27]</Sequence>
<Sequence>'office:version=' [22 27] '1.2' [22 27]</Sequence>
```
In the short term I guess replacing the dash for a colon will work (in the skeleton generator) but I haven't quite got to grips with all of the container syntax yet and so I think I'll need to revisit this in more depth soon.

**Comment by ross-spencer** [comment]
This should be fixed with https://github.com/exponential-decay/skeleton-container-test-suite-generator/commit/9ef1d82142dc16a2c623017db708de24ca549d37 and there is a little additional logging. (In hindsight I might move this logging again as the processing module should be more independent).
