### ISSUE TITLE
no more happy path, always exits with code 1

### ISSUE THREAD

**Issue by richardlehane** [exponential-decay/skeleton-container-test-suite-generator#16]
The container generator always exits with an error code (sys.exit(1)) following [this commit](https://github.com/exponential-decay/skeleton-container-test-suite-generator/commit/6d766cb31e324e20ef3f7901f18c3f116ca5868f)

This is breaking my github action: https://github.com/richardlehane/builder/runs/5283775500?check_suite_focus=true as it halts on any step that returns an error code. There's a workaround where you can put "continue-on-error: true" to force the github action to keep running but this is a bit of a hack as would hide any real errors thrown by your script.

**Comment by ross-spencer** [comment]
@richardlehane thanks for reporting that, I believe it's fixed with https://github.com/exponential-decay/skeleton-container-test-suite-generator/commit/95b8328ac86a315f02d2d2e08bd6c61963708c89.

**Comment by richardlehane** [comment]
isn't the happy path this block: 

if args.con and args.sig:
        skeletonfilegeneration(args.con, args.sig, args.debug)
        sys.exit(1)

& shouldn't that sys.exit(1) be sys.exit(0)??

**Comment by ross-spencer** [comment]
🤦

You're right. Okay, so I reverted that, this commit should be better [b611469](https://github.com/exponential-decay/skeleton-container-test-suite-generator/commit/b611469996af31f37af80b25119abc0d5f896508).

**Comment by richardlehane** [comment]
sweet, that fixed it, thanks!
