### ISSUE TITLE
Generator attempts to create file when only a dir is specified, e.g. fmt/1196

### ISSUE THREAD

**Issue by richardlehane** [exponential-decay/skeleton-container-test-suite-generator#4]
![image](https://user-images.githubusercontent.com/157422/45664557-cb27e500-bb4f-11e8-81ff-2507aa4ce253.png)

**Comment by richardlehane** [comment]
Issue seems to be that there is no file to create, the signature just requires a SIARD directory within the zip file:
![image](https://user-images.githubusercontent.com/157422/45666363-86ed1280-bb58-11e8-8c35-e5e989b6609d.png)

**Comment by ross-spencer** [comment]
Thanks Richard. I should be able to fix this at the weekend.
