### ISSUE TITLE
range syntax: fmt/1348 & fmt/1352

### ISSUE THREAD

**Issue by richardlehane** [exponential-decay/skeleton-container-test-suite-generator#6]
[ranges.zip](https://github.com/exponential-decay/skeleton-container-test-suite-generator/files/4094325/ranges.zip)

These container signatures both have ranges in the pattern e.g. `00 00 00 00 [01-04]`

The range seems to be ignored by the generator (just puts 0 bytes there)

**Comment by ross-spencer** [comment]
Closing as duplicate of https://github.com/exponential-decay/skeleton-container-test-suite-generator/issues/11
